import java.util.Random;

public class SavingsAccount extends BankAccount{


    @Override
    public void showAccountBalance() {

        System.out.println(getAvailableBalance());
    }

    public SavingsAccount(String accountHolderName, String accountOpeningDate, String modeOfOperation, boolean internetAndMobileBanking, double totalBalance, double availableBalance, float interestRate, String accountStatus) {
        super(accountHolderName, accountOpeningDate, modeOfOperation, internetAndMobileBanking, totalBalance, availableBalance, interestRate, accountStatus);
        accountNo = autoGeneratedAccountNo();
    }

    public long autoGeneratedAccountNo() {
        long branchCodeSA = 4059;
        Random obj = new Random();
        long accountNo = branchCodeSA * 100000000 + obj.nextLong(100000000L);
        return accountNo;
    }

    public double debit(double amount) {
       setAvailableBalance(getAvailableBalance() - amount);
        return getAvailableBalance();
    }

    public double credit( double amount) {
        setAvailableBalance(getAvailableBalance() + amount);
        return getAvailableBalance();
    }

}