import java.util.*;


public class SavingsAccount {

    String accountType;
    int accountHolderAge;
    long accountNumber;
    String accountHolderName;
    int accountBalance;
    String accountStatus;


    //behaviour
    public long autoGeneratedAccountNo() {
        long branchCode = 4059;
        Random obj=new Random();
        long accountNumber = branchCode*100000000 + obj.nextLong(100000000L);
        return accountNumber;
    }
    public float deposit(float accountBalance, float depositedAmount){
        accountBalance = accountBalance + depositedAmount;
        return accountBalance;
    }
    public float withdraw(float accountBalance, float withdrawlAmount){
        if(accountBalance>withdrawlAmount) {
            accountBalance = accountBalance - withdrawlAmount;
        }
        return accountBalance;

    }
    public float transfer(float accountBalance, float transferedAmount){
        accountBalance = accountBalance - transferedAmount;
        return accountBalance;
    }
    public int accountBalance(){
        return accountBalance;

    }

    /*public String AccountStatus(int accountBalance){
        if (accountBalance < 0){
            accountStatus = "Inactive";
        }
        else accountStatus = "Active";
        return accountStatus;


    }*/


}

