import java.util.Random;
public class SavingsAccount {
        String accountType;
        int accountHolderAge;
        long accountNumber;
        String accountHolderName;
        double accountBalance;
        String accountStatus;

        SavingsAccount(String accountType, int accountHolderAge, String accountHolderName, int accountBalance) {
            this.accountType = accountType;
            this.accountHolderAge = accountHolderAge;
            this.accountNumber = autoGeneratedAccountNo();
            this.accountHolderName = accountHolderName;
            this.accountBalance = accountBalance;
            this.accountStatus = accountBalance<500?"Inactive":"Active";
        }

        public long autoGeneratedAccountNo() {
            long branchCode = 4059;
            Random obj = new Random();
            long accountNumber = branchCode * 100000000 + obj.nextLong(100000000L);
            return accountNumber;
        }

        public double deposit(double depositedAmount) {
            accountBalance += depositedAmount;
            return accountBalance;
        }

        public double withdraw(double withdrawlAmount) {
            if (accountBalance > withdrawlAmount) {
                accountBalance -= withdrawlAmount;
            }
            return accountBalance;
        }


        public double transfer(double amountToTransfer , SavingsAccount creditTo) {
            if (accountBalance > amountToTransfer) {
                accountBalance -= amountToTransfer;
                creditTo.deposit(amountToTransfer);
            }

            return accountBalance;
        }

        public double accountBalance() {
            return accountBalance;

        }

        public String updateAccountStatus() {
            if (accountBalance < 500) {
                accountStatus = "Inactive";
            } else accountStatus = "Active";
            return accountStatus;

        }
    }

